---
title: "PAKICETUS STOCK A (_Pakicetus sp_)"
author:
  - name: Carl Linnaeus
    email: carl.linnaeus@noaa.gov
    orcid: 0000-0001-111-1111
    affiliations:
      - ref: noaa-mml
  - name: Charles Darwin
    email: charles.darwin@noaa.gov
    affiliations:
      - ref: noaa-mml

affiliations:
  - id: noaa-mml
    name: Alaska Fisheries Science Center
    department: National Marine Fisheries Service
    address: 7600 Sand Point Way NE
    city: Seattle
    state: WA

execute: 
  echo: false
  warning: false
  message: false

format:
  html: 
    theme: cosmo
    fontsize: 1.1em
    linestretch: 1.7
  docx:
    reference-doc: ../templates/custom-reference-doc.docx
---

```{r packages, include = FALSE}
library(sf)
library(dplyr)
library(rnaturalearth)
library(rnaturalearthhires)
```


## STOCK DEFINITION AND GEOGRAPHIC RANGE 

This section should summarize stock designation and DIP delineation information. This information should include a summary of the lines of evidence that support DIP delineations, and cite any supporting documents where this information is detailed. This section should also include a description of what is known about the geographic range of the stock (and a map if appropriate), including any known stock boundaries if applicable, and any uncertainty regarding the stock range. See Section 3.1 for additional guidance

## POPULATION SIZE 

This section should describe what is known about the size of the stock. It should include specific sub headings entitled “Minimum Population Estimate” and “Current Population Trend” describing these two characteristics of the stock. It may include additional sub headings as appropriate such as “Earlier abundance estimates”, “Recent surveys and abundance estimates”, and “Historical abundance”, among others. See Section 3.2.1 and 3.2.2 for additional guidance.

## CURRENT AND MAXIMUM NET PRODUCTIVITY RATES 

This section should describe what is known about the current and maximum net productivity rates. Default values should be used for Rmax in the absence of stock-specific measured values. See Section 3.2.3 for additional guidance. 

## POTENTIAL BIOLOGICAL REMOVAL 

This section of the SAR should provide a summary of the values used to calculate PBR and details its calculation. See Section 3.2 for additional guidance. 

## ANNUAL HUMAN-CAUSED MORTALITY AND SERIOUS INJURY 

This section should contain a complete description of what is known about human-caused M/SI for the covered time period. It should include a specific sub heading entitled “Fisheries Information” that describes fishery-related M/SI and may include other sub headings as appropriate, such as “Alaska Native Subsistence/Harvest Information”, and “Other Mortality”, among others. See Section 3.3 for additional guidance. 

## STATUS OF STOCK 

This section should summarize four types of “status” of the stock: (1) current legal designation under the MMPA and ESA, (2) status relative to OSP (within OSP, below OSP, or unknown), (3) designation of strategic or not, and (4) a summary of trends in abundance and human-caused M/SI. See Section 3.4 for additional guidance.

## OTHER FACTORS THAT MAY BE CAUSING A DECLINE OR IMPEDING RECOVER Y 

This section, which is required for strategic stocks but otherwise optional, should describe any other factors affecting the status of the stock. It should only be a summary of the issue and should reference publications. See Section 3.5 for additional guidance. 

## REFERENCES CITED 

This section should include a bibliography of references used to support the SAR. 
