on:
  workflow_dispatch:
  push:
    branches: [ main ]

name: Publish Pakicetus SAR

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      
      - name: Install cURL Headers
        run: sudo apt-get install libcurl4-openssl-dev
      
      - name: Install sf dependencies
        run: |
          sudo apt-get install libudunits2-dev
          sudo apt-get install libgdal-dev
          sudo apt-get install libgeos-dev
          sudo apt-get install libproj-dev
      
      - name: Install protobuf
        run: |
          sudo apt-get install libprotobuf-dev
          sudo apt-get install protobuf-compiler
      
      - name: Install jqr
        run: sudo apt-get install libjq-dev      

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
      
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::sf
            any::dplyr
            any::here
            any::ggplot2
            any::rnaturalearth
            any::ragg
            any::knitr
            any::rmarkdown
            any::ggtext
            any::rcartocolor
            
      - name: Install rnaturalearthhires
        run: |
          R -e 'install.packages("rnaturalearthhires", repos = "http://ropensci.r-universe.dev", type = "source")'
        
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

